preprocessing:
  enabled: true

  text_column: "Текст Сообщения"
  lowercase: true
  remove_html: true
  remove_non_alpha: true
  extra_stopwords: ["это", "который", 'ас', 'г', 'д', 'е', 'ул']
  use_stemming: false
  use_lemmatization: true
  ngram_range: [1, 2, 3]

models:

# --- Модель -------------------------------------------------------------------
# Варианты:
#     'log_reg': LogRegModel,
#     'catboost': CatBoostModel,
#     'rubert': RuBERTModel,
#     'ensemble': EnsembleModel
  name: rubert
  fine_tune_mode: full # ['full', 'gradual']
  # Специфичные для модели гиперпараметры, распаковываются как **kwargs
  # в build_model() / model.train() (например, epochs, learning_rate, iterations)
  params: {}

data:
  num_labels: 17
  test_size: 0.2
  val_size: 0.1
  random_state: 42

logging:
  log_dir: "logs"
  level: "INFO"

mlflow:
  enabled: true
  tracking_uri: "file:./mlruns"
  experiment_name: "nlp_classification"
