preprocessing:
  enabled: true
  text_column: "Текст Сообщения"
  lowercase: true
  remove_html: true
  remove_non_alpha: true
  extra_stopwords: ["это", "который", 'ас', 'г', 'д', 'е', 'ул']
  use_stemming: false
  use_lemmatization: true
  ngram_range: [1, 2, 3]

model:
  kind: log_reg
  C: 1
  max_iter: 1000
  ngram_range: [1, 4]

  # kind: catboost
  # iterations: 1000
  # learning_rate: 0.03
  # ngram_range: [1, 3]

  # kind: rubert
  # fine_tune_mode: full
  # learning_rate: 2.0e-5
  # num_train_epochs: 20
  # max_length: 256

data:
  path: 'data/raw/train_dataset_train.csv'
  test_size: 0.2
  val_size: 0.1
  random_state: 42

logging:
  log_dir: "logs"
  level: "INFO"

tracking:
  enabled: true
  tracking_uri: "file:./mlruns"
  experiment_name: "nlp_classification"
