preprocessing:
  preprocessing: false
  text_column: "Текст Сообщения"
  lowercase: true
  remove_html: true
  remove_non_alpha: true
  extra_stopwords: ["это", "который", 'ас', 'г', 'д', 'е', 'ул']
  use_stemming: false
  use_lemmatization: true
  ngram_range: [1, 2, 3]

models:

# --- Модель -------------------------------------------------------------------
# Варианты:
#     'log_reg': LogRegModel,
#     'catboost': CatBoostModel,
#     'rubert': RuBERTModel,
#     'ensemble': EnsembleModel
  MODEL_NAME: rubert
  
train:
